// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// orthoKMeansTrainCpp
List orthoKMeansTrainCpp(Rcpp::NumericMatrix x, unsigned long int rounds, unsigned long int k, unsigned long int iter, unsigned long int initType, bool verbose);
RcppExport SEXP yakmoR_orthoKMeansTrainCpp(SEXP xSEXP, SEXP roundsSEXP, SEXP kSEXP, SEXP iterSEXP, SEXP initTypeSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< unsigned long int >::type rounds(roundsSEXP);
    Rcpp::traits::input_parameter< unsigned long int >::type k(kSEXP);
    Rcpp::traits::input_parameter< unsigned long int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< unsigned long int >::type initType(initTypeSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    __result = Rcpp::wrap(orthoKMeansTrainCpp(x, rounds, k, iter, initType, verbose));
    return __result;
END_RCPP
}
// orthoKMeansPredictCpp
List orthoKMeansPredictCpp(NumericMatrix x, std::vector <NumericMatrix> centers, unsigned long int nf, unsigned long int k, bool verbose);
RcppExport SEXP yakmoR_orthoKMeansPredictCpp(SEXP xSEXP, SEXP centersSEXP, SEXP nfSEXP, SEXP kSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::vector <NumericMatrix> >::type centers(centersSEXP);
    Rcpp::traits::input_parameter< unsigned long int >::type nf(nfSEXP);
    Rcpp::traits::input_parameter< unsigned long int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    __result = Rcpp::wrap(orthoKMeansPredictCpp(x, centers, nf, k, verbose));
    return __result;
END_RCPP
}
